### ISSUE TITLE
TFC Rest API Provider

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#1374]
# TFC Rest API Provider

## Problem Statement

As a user I want to see the workspaces and runs I have permissions to view inside VS Code so I can interact with TFC while I code in my editor.

## Expected User Experience

This is not a user facing feature. This is needed as having a centralized way of retreiving data from TFC.

We will need to call TFC to authenticate the user, list workspaces and runs, and obtain details for workspaces and runs.

## Proposal

We are going to have several places that will need to request or display data from TFC so a centralized place to deal with the details of crafting a HTTP request and serializing the response will be valuable.

We will have to decide where to query TFC from, either from the client (VS Code) or from the server (terraform-ls).

Querying from inside VS Code makes the most sense when want speed and the ability to support web based extensions. Since it is part of the client UI, we won't be competing with the other operations terraform-ls has to perform like indexing the workspace or querying the registry for provider information, etc. Adding more REST API calls to this could impact server side performance. Keeping this client side also means we do not have to round trip the information queried from TFC to terraform-ls then over JSONRPC wrapped stdin to VS Code. We also get direct access to UI features like progress reporting. There is existing prior-art in [terraform-cdk](https://github.com/hashicorp/terraform-cdk/blob/d6534cbbe9af5942a0fb8d95c3cfa38f827fac5e/packages/cdktf-cli/src/bin/cmds/helper/terraform-cloud-client.ts) that uses Typescript to access TFC, so we would not be starting from scratch.

Querying from inside terraform-ls makes the most sense if we want to prioritize client portability. We write the logic once, then all clients can call the same commands to receive data. This results in the most portability and flexibility. In practice, it is likely that only VS Code has the UI to display the features we want to show. There is an existing Go library called [go-tfe](https://github.com/hashicorp/go-tfe), so there is work to either use outright or build on.

## Requirements

All requests must be authenticated with a bearer token. Use the HTTP header `Authorization` with the value `Bearer <token>`.

All requests must contain a UTM to identify that they are coming from our extension for TFC telemetry tracking

In general, we should not implement Create, Update or Deletion of any items . Should only implement Read. While this is technically possible using TFC API, it puts us in the business of making a UI around creation or modification which has some business rules around it.

## Documentation

TFC API calls

Documentation:
  General docs: https://developer.hashicorp.com/terraform/cloud-docs/api-docs
  Workspaces: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces
  Runs: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run

To Implement:

List Workspaces: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces#list-workspaces
Workspace Detail: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces#show-workspace
Workspace Performance attributes: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces#workspace-performance-attributes
Lock Workspace: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces#lock-a-workspace

List Runs: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#list-runs-in-a-workspace
Run Detail: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#get-run-details
Create Run: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#create-a-run
Apply Run: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#apply-a-run
Discard Run: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#discard-a-run
Cancel Run: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#cancel-a-run

## Tickets

- [x] (Internal) Reach out to TFC team to get a UTM for us to use
- [x] (Discovery) Determine the location to query TFC from (client or server)
- [x] #1400
- [x] #1401
- [x] Implement Get Workspace Detail
- [x] #1402
- [x] Implement Get Run Detail

**Comment by dbanck** [comment]
I favor implementing this in the VS Extension; I don't expect us to write much logic or data transformation inside the API wrapper. Instead, the main work will be building the UI, which is client-sided anyway. If another editor chooses to implement a similar UI in the future, adapting the API provider should be easily doable.

Doing everything client-sided saves us from multiple round-trips, marshaling, and unmarshaling JSON twice. Instead, the language server can focus on parsing the config while the extension communicates with the TFC API.

If we want to support a private registry for modules and providers in the future, we can still pass the authenticating information to the LS while keeping workflow and runs client-sided.
