### ISSUE TITLE
TFC Readonly Runs View

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#1395]
## Problem Statement

As a user I want to see the runs for a selected workspace I have permissions to view inside VS Code so I can interact with TFC while I code in my editor.

## Expected User Experience

I should see a list of runs in a tree view from the workspace I selected that I have permission to view. Expanding a run shows run details. Each run tree item has commands like view apply log and navigate to TFC website for that run.

## Proposal

Implement a new TreeDataprovider for TFC Runs utilizing the TFC Rest API defined in epic https://github.com/hashicorp/vscode-terraform/issues/1374. This will use the TFC token provided by the Authentication provided in epic https://github.com/hashicorp/vscode-terraform/issues/1373.

Implement a TreeView for runs inside the Terraform sidebar, which lists Run Tree Items. This view will be populated from the selected workspace in the Workspace Tree View.

Attention to paging will be key here. It is common to have many tens or hundreds of runs, so filtering or searching for them will be a key user experience.

Both the VS Code Tree View UI and the TFC API provide ways of filtering and displaying filtered results.

## Documentation

List runs for selected workspace: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#list-runs-in-a-workspace
Show run detail: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#get-run-details

Actions
Open run in TFC web in browser: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#get-run-details
Create new run action: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run
Apply a run action: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#apply-a-run
Discard a run action: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#discard-a-run
Cancel a run action: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#cancel-a-run

## Tickets

- [x] Implement new Run Tree View Provider (#1451)
- [x] Implement new Run Tree View underneath Workspace View (#1451)
- [x] Implement Open Run in TFC Website command (#1451)
- [x] #1457
- [x] #1458

### Descoped

- [ ] Implement Create new run command
- [ ] Implement Plan a run command
- [ ] Implement Apply a run command
- [ ] Implement Discard a run command
- [ ] Implement Cancel a run command
