### ISSUE TITLE
Provider-defined functions support

### ISSUE THREAD

**Issue by dbanck** [hashicorp/vscode-terraform#1674]
## Background

Terraform will introduce provider-defined functions in an upcoming release. This will allow provider authors to ship their own functions. Practitioners will be able to use them in their Terraform configuration using a new function call syntax: `provider::aws::noop()`.

We currently support all built-in core functions as static definitions in terraform-schema. The provider functions will be part of the provider schema JSON and should be parsed whenever we get a provider schema (bundled or via CLI). Both need to be merged into a single list of function signatures.

## Expected User Experience

Syntax highlighting, completion, hover, semantic tokens, and signature help are working as expected for provider-defined functions.

![completion](https://github.com/hashicorp/vscode-terraform/assets/45985/1a3d0eda-0920-4940-8673-5024437151c9)

![signature help](https://github.com/hashicorp/vscode-terraform/assets/45985/2ffa45ca-79b1-43fc-ac32-920b4981431c)

## Proposal

**hcl**
- [x] Fix NameRange for `FunctionCallExpr`
  - [x] https://github.com/hashicorp/hcl/issues/650

**hcl-lang**
- [x] Stability improvement for `nil` expressions
  - [x] In the [earlydecoder](https://github.com/hashicorp/terraform-schema/blob/f5a142dc9b98cf62b79ba1bae3ecbdb2fd156fdd/earlydecoder/load_module.go#L282) -> [PR](https://github.com/hashicorp/terraform-schema/pull/324)
  - [x] In the [decoder package](https://github.com/hashicorp/hcl-lang/tree/main/decoder) -> [PR](https://github.com/hashicorp/hcl-lang/pull/376)
- [x] https://github.com/hashicorp/hcl-lang/pull/372

**terraform-json**
- [x] https://github.com/hashicorp/terraform-json/pull/119

**terraform-schema**
- [x] https://github.com/hashicorp/terraform-schema/issues/320 -> [PR](https://github.com/hashicorp/terraform-schema/pull/321)

**terraform-ls**
- [x] hashicorp/terraform-ls#1613 -> [PR](https://github.com/hashicorp/terraform-ls/pull/1636)

**syntax**
- [x] https://github.com/hashicorp/syntax/issues/98 -> [PR](https://github.com/hashicorp/syntax/issues/99)

---

### Stretch Goals

- [x] https://github.com/hashicorp/vscode-terraform/issues/1697

**Comment by ansgarm** [comment]
Posting my findings about the earlydecoder output stuff that is causing `nil` panics here:
The value of outputs seems to indeed be used, well to be precise, its type is:
https://github.com/hashicorp/terraform-schema/blob/0c03703f91f7085f9f2910e7e79f214c9f913ad0/schema/module_schema.go#L159

The value itself is also stored in a map, but that one is never read.

So, I don't think we can remove the handling there, but we can ignore `nil` expressions.

**Comment by dbanck** [comment]
Shipped 🎉
