### ISSUE TITLE
Terraform Stacks Editor Support

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#1699]
### Problem Statement

Terraform Stacks is a new way of organizing Terraform infrastructure-as-code configurations. A Terraform stack represents a graph of interconnected components that are managed across many independent deployments.

The authoring stage will be one of the primary interface points for Terraform Stacks users. Having and editor provide support for Terraform Stacks files would ease the use of Stacks for new users and enable advanced users with more complex configurations.

### Proposal

In the initial preview a user will author Terraform Stack configurations and initiate a deployment by merging code to a GitHub repository that is linked with Terraform Cloud. When the merge happens TFC plans and applies the stack according to the deployment file.

The intellisense, inline documentation, syntax validation and other advanced language features of the Terraform Extension for VS Code will provide a guided introduction to using Stacks as well as powerful introspection through deep reference parsing for advanced users.

Support will be delivered in a phased manner:

Phase 1: Basic Language Support

- [x] Claim new language identifiers and file extensions
- [x] Syntax highlighting support for new keywords
- [x] Add new schema to terraform-schema
- [x] Add support for completion, hover and semantic tokens of new language keywords and existing provider schema

Phase 2: Complex Language Support

- [x] Add complex support for completion, hover and semantic tokens of new language keywords and existing provider schema
- [x] Reference target and origin resolution
- [x] Inputs and outputs completion between stacks, components and deployments

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
