### ISSUE TITLE
Make Terraform extension available in "browser mode"

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#768]
## Problem Statement

GitHub employees and other users use VS Code in the browser for various reasons.
This extension currently isn't available for them.

Example https://github.dev/hashicorp/terraform-guides

<img width="809" alt="Screenshot 2021-09-14 at 10 56 15" src="https://user-images.githubusercontent.com/287584/133237039-37c9068f-a6d0-4755-bd54-76f5c9b8ebc2.png">

## Expected User Experience

Extension is available to assist users in editing Terraform code in their browser, the same way as in desktop VS Code.

For example at https://vscode.dev/ or https://github.dev/

## Proposal

https://code.visualstudio.com/docs/remote/codespaces#_why-is-an-extension-not-installable-in-the-browser

There is some documentation here: https://code.visualstudio.com/api/extension-guides/web-extensions

We could initially provide just a minimal extension for the web - e.g. with syntax highlighting only.

 - [x] Investigate impact on telemetry logic
 - [x] Investigate replacing of esbuild with webpack
 - [x] Create browser entrypoint and link it from `package.json` per docs, e.g. `"browser": "./dist/web/extension.js",`

Longer-term we'd need to find out if there's any way or benefit from running LS in the browser - either via WASM or GopherJS.

**Comment by andymac4182** [comment]
This would be awesome! I have been doing lots of PR reviews in the browser with github.dev

**Comment by Satak** [comment]
Please make this available for github codespaces.

**Comment by jpogran** [comment]
Hey @Satak, apologies for the delay in response. You should be able to use the extension in Codespaces:

![image](https://user-images.githubusercontent.com/272569/157525838-a74ab014-b4f9-4479-9a4d-53a7fc6b1755.png)

Intellisense and other advanced language features work:

![image](https://user-images.githubusercontent.com/272569/157526021-d3008de2-c562-470f-ad87-8a88b3da594b.png)

**Comment by Satak** [comment]
But it is not available for Codespaces in web browser:

![image](https://user-images.githubusercontent.com/10957012/157600413-9e568c7d-0474-47c3-b6b8-a4abdeeef8f5.png)

**Comment by jpogran** [comment]
Yep! I misunderstood what you were referring to because the two are called different things: https://docs.github.com/en/codespaces/the-githubdev-web-based-editor

We currently work in the full Codespaces environment. We don't yet work in the web-based editor.

**Comment by jpogran** [comment]
I am exceedingly happy to announce, that as of v2.25.0, we now work in github.dev and vscode.dev in the browser!

**Comment by radeksimko** [comment]
As mentioned, we provide a basic web version of the extension from `v2.25.0`, therefore I am going to close this issue. I have however created a separate one in https://github.com/hashicorp/vscode-terraform/issues/1287 to track possible future enhancements in this area. Comments are welcomed there.
